setwd("M:/users/matheus/mongo/crawler/results_2014_05_24-M3-R1")
library(ggplot2)
valores2 = read.csv("summarized_all_ordered_cost.csv", header = TRUE)
str(valores2)

valores2$instances <- factor(valores2$instances, order=TRUE)
valores2$workload <- factor(valores2$workload, order=TRUE)
valores2$instance_price <- factor(valores2$instance_price, order=TRUE)
valores2$total_price <- factor(valores2$total_price, order=TRUE)
valores2$price_provider_id <- mapply(function(x,y){paste(x,y,sep="_")}, valores2$instance_price, valores2$provider_id)
valores2$price_provider_id <- factor(valores2$price_provider_id, order=TRUE)
str(valores2)
valores2$provider_id <- factor(valores2$provider_id, levels = c("m3_m", "c3_l", "m3_l","c3_xl", "m3_xl", "c3_2xl", "m3_2xl"))
valores2$fc_cost_user <- factor(valores2$cost_user, order=TRUE)
valores2$provider_id <- factor(valores2$provider_id, levels = c("m3_m", "c3_l", "m3_l","c3_xl", "m3_xl", "c3_2xl", "m3_2xl"))

ggplot(subset(valores2, percentile < 30000), aes(x=instances, y=provider_id, size=total_price, colour=total_price)) +  facet_grid(. ~ workload)  + ggtitle("90th Response Time < 30 | workload + provider_id + User Cost") + geom_text (aes(label = total_price, angle = 0, hjust=0, vjust=-1), size = 2.5) + theme(legend.position = "none") + geom_point()


setwd("M:/users/matheus/mongo/crawler/results_2014_05_24-M3-R1")
performance = read.csv("performance.csv", header = TRUE, stringsAsFactors = FALSE)
str(performance)
performance$configuration <- mapply(function(x,y){paste(x,y,sep="_")}, performance$instances, performance$provider_id)
performance$vm_type <- factor(performance$vm_type, order=TRUE)
performance$provider_id <- factor(performance$provider_id, order=TRUE)
performance$workload <- factor(performance$workload, order=TRUE)
performance$cpubusy <- as.numeric(performance$cpubusy)
performance$cpubusy_fac <- cut(performance$cpubusy, breaks=4)
performance$instances <- factor(performance$instances, order=TRUE)
str(performance)
library(ggplot2)
ggplot(subset(performance, vm_type != "nginx"), aes(provider_id, fill=cpubusy_fac)) + facet_grid(instances  ~  workload * vm_type )+ geom_bar(position="fill") + coord_flip() + ggtitle("CPU Usage") + guides(size=FALSE)
